name: Full Scan with ZAP Action

on:
  push:
    branches:
      - main

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Scan the web application
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: "http://hack-yourself-first.com/"
      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html
